### PR TITLE
Updates for review feedback

### PR DESCRIPTION
**Pull request by jasongin**
- Delete the `node_api_*internal.h` headers - there is no longer any reason for their contents to be separate from the `.cc` files.
 - Always set callback data internal field to prevent crashing when `V8_ENABLE_CHECKS` is defined
 - Don't crash when casting numbers when `V8_ENABLE_CHECKS` is defined
 - Return 0 when getting NaN value as an integer (also fixes https://github.com/nodejs/abi-stable-node/issues/124)
 - Style: replace `if (ptr)` with `if (ptr != nullptr)`
 - Fix extern "C" in `node_api_async.h`
 - Minor doc changes

### CODE REVIEW

**Comment by jasongin** [comment]
Addresses all of today's feedback on the PR at https://github.com/nodejs/node/pull/11975

**Comment by jasongin** [comment]
CI passed: https://ci.nodejs.org/view/x%20-%20Abi%20stable%20module%20API/job/node-test-commit-linux-abi/95/

**Comment by digitalinfinity** [comment]
:shipit:

**Review by digitalinfinity — APPROVED** [review]

**Review by boingoing — APPROVED** [review]
LGTM

**Pull request merged**
