### PR TITLE
tools: Distribute node_jsvmapi.h header

### PR DESCRIPTION
**Pull request by gabrielschulhof**
##### Checklist

- [x] tests and code linting passes
- [ ] a test and/or benchmark is included
- [ ] documentation is changed or added
- [x] the commit message follows commit guidelines

##### Affected core subsystem(s)

tools

##### Description of change

This is needed for building outside projects against the ABI stable API

### CODE REVIEW

**Comment by digitalinfinity** [comment]
Looks good to me- is this going to be merged into NodeJs/master or abi-stable-node/master?

**Comment by gabrielschulhof** [comment]
Oh! Wait a sec - I intended this to be merged into abi-stable-node/master ...

**Comment by gabrielschulhof** [comment]
I'll have to close and re-submit.

**Comment by gabrielschulhof** [comment]
https://github.com/nodejs/abi-stable-node/pull/6 - but that also seems to want to go into upstream. Weird - is this because abi-stable-node is a fork of node?

**Comment by digitalinfinity** [comment]
I wonder if it's just a quirk in the GitHub UI- node/master is the upstream node repo, nodejs is just the organization, and for some reason GitHub is showing the upstream is nodejs/master...anyway, your change looks fine but might want to wait for @mhdawson to confirm since my nodejs contribution-fu is non-existent 😄

**Comment by gabrielschulhof** [comment]
If you hover about the destination org/branch and the source org/branch then you see that the PR is going to the right repo. So, opening #6 was actually unnecessary.

**Comment by digitalinfinity** [comment]
Ah didn't know the hover text existed- that makes sense, even if it's slightly undiscoverable. Thanks for the tip @gabrielschulhof, sorry you had to unnecessarily close this PR.

**Pull request closed without merging**
