### PR TITLE
Node API rename

### PR DESCRIPTION
**Pull request by jasongin**
Fixes https://github.com/nodejs/abi-stable-node/issues/130

There are 4 commits in this PR, for the 4 kinds of renames that were performed. It will be a little easier to review them separately:
 * Rename `addons-abi` to `addons-napi`
 * Rename source files to `node_api_*`
 * Rename `NODE_MODULE_ABI` to `NAPI_MODULE`
 * Rename `addon_abi_register_func` to `napi_addon_register_func`

I will keep this PR open until at least the end of the day today, then rebase on top of any other changes that went in.

### CODE REVIEW

**Comment by jasongin** [comment]
CI passed: https://ci.nodejs.org/view/x%20-%20Abi%20stable%20module%20API/job/node-test-commit-linux-abi/41/

**Review by mhdawson — APPROVED** [review]
LGTM

**Review by digitalinfinity — APPROVED** [review]
LGTM

**Review by boingoing — APPROVED** [review]
Looks great 👍

**Pull request merged**
