### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by gabrielschulhof**

### CODE REVIEW

**Comment by gabrielschulhof** [comment]
@nodejs/n-api I would like to recommend in https://github.com/nodejs/node/pull/22801 that the PR be made against this README.md rather than the main N-API reference doc. Thus, I believe that PR depends on this PR.

**Review by NickNaso — APPROVED** [review]
LGTM

**Review by mhdawson — APPROVED** [review]
LGTM

**Comment by gabrielschulhof** [comment]
Landed in 8a49c13cf56cac66e83f1a1559e78188f51f10a0.

**Pull request closed without merging**
