### PR TITLE
napi, test: Fix eslint errors

### PR DESCRIPTION
**Pull request by digitalinfinity**
Fixes eslint errors in the test js files
Generally trivial mechanical transformation

Refs: https://github.com/nodejs/abi-stable-node/issues/126

### CODE REVIEW

**Comment by digitalinfinity** [comment]
I'll deal with the cpplint errors next. @mhdawson @jasongin @gabrielschulhof please take a look

**Review by jasongin — APPROVED** [review]

**Review by mhdawson — APPROVED** [review]
LGTM

**Comment by mhdawson** [comment]
CI run: https://ci.nodejs.org/view/x%20-%20Abi%20stable%20module%20API/job/node-test-commit-linux-abi/14/

**Comment by digitalinfinity** [comment]
@jasongin @mhdawson thanks for the reviews! @gabrielschulhof do you want to take a look too or should I go ahead and merge?

**Comment by mhdawson** [comment]
CI run is green so go ahead and land.  For core there is a 48 hour waiting period for objections, but since we're a smaller group here I think you are good to land.

**Comment by digitalinfinity** [comment]
Landed in e61a100

**Pull request merged**
