### PR TITLE
test: fix missing initializer warnings at build

### PR DESCRIPTION
**Pull request by sampsongao**

### CODE REVIEW

**Review by jasongin — APPROVED** [review]

**Review by boingoing — APPROVED** [review]
LGTM

**Review by mhdawson — APPROVED** [review]
LGTM

**Comment by mhdawson** [comment]
CI run: https://ci.nodejs.org/view/x%20-%20Abi%20stable%20module%20API/job/node-test-commit-linux-abi/43/

**Comment by mhdawson** [comment]
Looks like something else landed and this needs to be rebased now.

**Comment by jasongin** [comment]
Landed as https://github.com/nodejs/abi-stable-node/commit/111160e3c7f31e8c706b2ed0390b05b1713cf8c9

**Pull request closed without merging**
