### PR TITLE
napi: Fix new lint errors

### PR DESCRIPTION
**Pull request by digitalinfinity**
Removed BOM from files
Removed trailing whitespace
Wrapped a couple lines

Fixes: #159

### CODE REVIEW

**Review by jasongin — APPROVED** [review]

**Comment by jasongin** [comment]
Oh, hmm... it appears all the tests rely on that cast because they omit the last `priv` parameter from the registration callback. Now I'm not sure what to do here...

**Review by boingoing — APPROVED** [review]
My bad, these all look to be due to the merge with my propertyname change.

LGTM

**Review by mhdawson — APPROVED** [review]
LGTM

**Comment by mhdawson** [comment]
CI: https://ci.nodejs.org/view/x%20-%20Abi%20stable%20module%20API/job/node-test-commit-linux-abi-mdawson/8/nodes=ubuntu1404-64/console

CI looks good.

**Comment by mhdawson** [comment]
Landed as 93fe9fb52beae4f81200b5f97e04657ef7a65557

Also update CI to add lint step, new run to validate: https://ci.nodejs.org/view/x%20-%20Abi%20stable%20module%20API/job/node-test-commit-linux-abi/48/

**Comment by mhdawson** [comment]
Second CI run good, closing.

**Pull request closed without merging**
