### PR TITLE
Address some minor PR feedback

### PR DESCRIPTION
**Pull request by jasongin**
Addressing several comments [in the PR](https://github.com/nodejs/node/pull/11975):
 - Simplify conversion to/from napi_value
 - Better names for CallbackWrapper template params
 - Fatal error when trying to set setter return value
 - Use node::arraysize
 - Replace v8::Handle with v8::Local
 - Align the star after v8::Isolate

Also:
 - Remove some non-ascii whitespace chars that were
   causing some IDEs to auto-add a UTF-8 BOM

### CODE REVIEW

**Comment by jasongin** [comment]
CI passed: https://ci.nodejs.org/view/x%20-%20Abi%20stable%20module%20API/job/node-test-commit-linux-abi/66/

**Review by digitalinfinity — APPROVED** [review]
LGTM

**Review by mhdawson — APPROVED** [review]
LGTM with question about whitespace changes

**Comment by jasongin** [comment]
@mhdawson What question about whitespace changes? Did you see the note about whitespace in the PR description?

**Review by boingoing — APPROVED** [review]
LGTM 👍

**Comment by jasongin** [comment]
CI after rebase and merge: https://ci.nodejs.org/view/x%20-%20Abi%20stable%20module%20API/job/node-test-commit-linux-abi/81/

**Review by gabrielschulhof — APPROVED** [review]

**Comment by jasongin** [comment]
CI after rebase and merge, again: https://ci.nodejs.org/view/x%20-%20Abi%20stable%20module%20API/job/node-test-commit-linux-abi/87/

**Pull request merged**
